version: "3"
services:
  slackbot:
    image: jurzo/bot-fork
    ports:
      - 3000:3000
    container_name: slackbot
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower